config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :comments, only: :destroy
  resources :pins do
    member do
      # acts_as_votable:
      put 'like', to: 'pins#upvote'       # PUT /pins/:id/like      like_pin_path( @pin )
      put 'dislike', to: 'pins#downvote'  # PUT /pins/:id/dislike   dislike_pin_path( @pin )
    end
    resources :comments, only: :create
  end

  # get    'pins',          to: 'pins#index'
  # get    'pins/new',      to: 'pins#new', as: 'new_pin' # must precede greedy `GET 'pins/:id'`
  # post   'pins',          to: 'pins#create'
  # get    'pins/:id',      to: 'pins#show', as: 'pin' # must name conventionally
  #                                                    # for `redirect_to @pin` to work
  #                                                    # because 3 other verbs act on 'pins/:id'
  #                                                    # ( PATCH, PUT, DELETE )
  # get    'pins/:id/edit', to: 'pins#edit', as: 'edit_pin'
  # match  'pins/:id',      to: 'pins#update', via: [:patch, :put]
  # # patch 'pins/:id',      to: 'pins#update'
  # # put   'pins/:id',      to: 'pins#update'
  # delete 'pins/:id',      to: 'pins#destroy'

  # 12-8-16: for debugging saga of plural and singular, see /lib/notes/debugging
  # 12-6-16: add user profiles
  resources :profiles,      only: [:index, :show]
  get       'profile/edit', to: 'profiles#edit',   as: 'edit_profile'
  match     'profile',      to: 'profiles#update', as: 'update_profile', via: [:patch, :put]

  root 'pins#index'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv": "Content-Type" }
    %title A04PinBoard
    =csrf_meta_tags
    =stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    =javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-default
      .container
        .navbar-brand= link_to 'Pin Board', root_path
        %ul.nav.navbar-nav.navbar-right
          -if user_signed_in?
            %li= link_to '+ Pin', new_pin_path
            %li= link_to 'Account', edit_user_registration_path
            %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
          -else
            %li= link_to 'Sign Up', new_user_registration_path
            %li= link_to 'Sign In', new_user_session_path

    .container
      -flash.each do |name, msg|
        =content_tag :div, msg, class:"alert alert-info"

      = yield